config/routes.rb
DailyTrack::Application.routes.draw do

  resources :manhours
   resources :inspections

  devise_for :admins
  devise_for :users 

 resources :users

  root 'welcome#home'

  resources :daily_reports do
      resources :daily_reports, only: [:new, :index, :show, :create,]
      resources :narratives,only: [:show, :create, :destroy,]
  end 

  resources :project_dashboards, only: [:index, :show, :create, :destroy] do
      collection {post :import}
  end

  resources :lead_reports, only: [:index]
  resources :project_visuals, only: [:index]
  resources :test, only: [:index] 
  resources :data_visuals, only: [:index] 
  resources :export_dashboard, only: [:index] 
  resources :inspections,only: [:index,:show,:edit,:organization]
  
  resources :inspection_reports do
      resources :inspections,only: [:show, :create, :destroy, :edit] 
      resources :notes,only: [:show, :create, :destroy] 
      resources :forces,only: [:show, :create, :destroy] 
      collection {put :approved}

  end

 resources :graph, only: [:index] 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/concrete_summary.rb
require 'csv'

class ConcreteSummary < ActiveRecord::Base
	attr_accessible :date, :baseline_early_ind, :baseline_early_cum, :baseline_late_ind, :baseline_late_cum 


	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			ConcreteSummary.create! row.to_hash
			#binding.pry
		end
	end


	
end

app/models/daily_report.rb
class DailyReport < ActiveRecord::Base
	attr_accessible :narrative, :date
	has_many :inspections
	has_many :narratives
	before_create :ensure_date
	
	def ensure_date
		self.date = Date.today unless self.date
	end 	

	has_attached_file :image, styles: {
	    thumb: '100x100>',
	    original: '250x250>'
	}
	
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.ensure_today
		daily_reports = DailyReport.where(date: Date.today)
    
		# ternary operator
		daily_report = daily_reports.present? ? daily_reports.first : DailyReport.create
		# daily_report = if daily_reports.present? 
		#     daily_reports.first 
		#   else 
		#     DailyReport.create
		# end

		daily_report
	end
	
	def self.to_csv
		CSV.generate do |csv|
		csv << column_names
			all.each do |wall|
			csv << wall.attributes.values_at(*column_names)
			end	
		end
	end

end

app/models/force.rb
class Force < ActiveRecord::Base
	attr_accessible :heading, :union147, :union15, :union14, :union731, :union3
	belongs_to :inspection_report
end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
	attr_accessible :heading, :element, :start, :finish, :operation, :scope, :note, :inspector
	 belongs_to :inspection_report
   belongs_to :daily_report
   before_save :ensure_daily_report
	 has_attached_file :image, 
   :styles => { :original => ['250x250>'],:thumb =>['100x100>'] },
   :default_url => "missing.png"

  def ensure_daily_report
    self.daily_report = DailyReport.ensure_today unless self.daily_report
  end

	 validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.search_for(query)
    where('heading LIKE :query OR element LIKE :query OR operation LIKE :query OR inspector LIKE :query ', query: "%#{query}%")
  end
end 

app/models/inspection_report.rb
class InspectionReport < ActiveRecord::Base
attr_accessible :inspector, :date, :contract, :contractor, :shift, :status

	has_many :inspections
	has_many :notes
	has_many :forces

	belongs_to :user

end

app/models/labor.rb
class Labor < ActiveRecord::Base
end

app/models/manhour.rb
class Manhour < ActiveRecord::Base
	attr_accessible :heading
	belongs_to :inspection_report

end

app/models/narrative.rb
class Narrative < ActiveRecord::Base
	attr_accessible :narrative
	belongs_to :daily_report

end

app/models/note.rb
class Note < ActiveRecord::Base
	attr_accessible :observation
	belongs_to :inspection_report
end

app/models/project_dashboard.rb
class ProjectDashboard < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :username, :email, :password, :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 	has_many :inspection_reports


  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "user_prrofile_1.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/lead_reports_controller.rb
class LeadReportsController < ApplicationController

  def index
    @daily_report= DailyReport.ensure_today  
    @inspections = @daily_report.inspections.order(created_at: :asc)  
    @walls = @daily_report.inspections.where("element = ?", "WALL").order(created_at: :asc) 
    @slabs = @daily_report.inspections.where("element = ?", "SLAB").order(created_at: :asc) 
    @arches = @daily_report.inspections.where("element = ?", "ARCH").order(created_at: :asc)  
    @user = current_user

		@brian_reports = InspectionReport.where(:inspector => "Brian_S")
		@howard_reports = InspectionReport.where(:inspector => "Howard_Y")
		# @howard_reports = InspectionReport.where(:inspector => "Oleg_Mosh")

		@brian_report_latest = InspectionReport.where(:inspector => "Brian_S").last
		@howard_report_latest = InspectionReport.where(:inspector => "Howard_Y").last
		# @howard_report_latest = InspectionReport.where(:inspector => "Oleg_Mosh").last


		# where(:inspector => current_user.username)
		@users = User.all
		@oleg = @users[2].username
		@inspection_report_current =InspectionReport.where(:inspector => "Oleg_Mosh").last
		# @user = current_user

  end




end

app/helpers/forces_helper.rb
module ForcesHelper
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/helpers/lead_reports_helper.rb
module LeadReportsHelper
end

app/helpers/manhours_helper.rb
module ManhoursHelper
end

app/helpers/narratives_helper.rb
module NarrativesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lead_reports/index.html.erb
      <!-- Navigation -->
      <div class="container"> 
        <div class="header">
            <ul class="nav nav-pills pull-right">
                <!-- <li><%= link_to 'Concept', project_visuals_path  %></li> -->
                <li><%= link_to 'Inspection Report', inspection_reports_path  if current_user  %></li>  
                <li><%= link_to 'Daily Report', daily_reports_path  if current_user && current_user.admin? %></li>
                <li><%= link_to 'Lead Report', lead_reports_path  if current_user && current_user.admin? %></li>
                <li><%= link_to 'Search', inspections_path  if current_user && current_user.admin? %></li>
                <li><%= link_to 'Profile', users_path  if current_user  %></li>
                <li><%= link_to 'Enter', users_path  if !current_user  %></li>
                <li> <%= button_to "Sign out", destroy_user_session_path , :class => "btn btn-link" , method: :delete  if current_user%></li>
            </ul>
          <h2 ><%= link_to 'Daily Track', root_path%><h2>
        </div>
      </div> 


<div class = "container">
  <h1 class="text-center ">Lead Report</h1>
  <div class="text-center ">  
  <br>     
  <p ><%= image_tag(@user.image.url(:thumb)) %></p>
<br>
<p>Howard</p>
<div class ="btn btn-link"><%=link_to @howard_report_latest.date ,inspection_report_path(@howard_report_latest)%></div>

<div class='row'>
        <div class ='span4'>
        </div>

<div class ='span4'>
<div class = "text-center">  
    <u id="flip" class="btn btn-link" ><h4> Howard All Reports</h4> </u>
</div>

<table class = "table" id = "panel" style=" display: none;" >
          <tr>
            <td >Date</td>
            <td >Status</td>
          
          </tr>
          <% @howard_reports.reverse_each do |inspection_report| %>
          <tr>    
            <td ><strong><%= link_to inspection_report.date, inspection_report_path(inspection_report) %><strong></td>
            <td ><strong><%= link_to inspection_report.status, inspection_report_path(inspection_report) %><strong></td>

          </tr>
        <% end %>
      </table>






  <div class = "table" id = "panel" style=" display: none;" >

      <% @howard_reports.reverse_each do |inspection_report| %>
      <p><strong><%= link_to inspection_report.date, inspection_report_path(inspection_report) %><strong></p>


  <% end %>
  </div>
  
</div>
</div>




<script type="text/javascript">
$(document).ready(function(){
    $("#flip").click(function(){
    $("#panel").slideToggle("slow");
    });
    });

</script>