config/routes.rb
DailyTrack::Application.routes.draw do

  resources :manhours
   resources :inspections

  devise_for :admins
  devise_for :users 

 resources :users

  root 'welcome#home'

  resources :daily_reports do
      resources :daily_reports, only: [:new, :index, :show, :create,]
      resources :narratives,only: [:show, :create, :destroy,]
  end 

  resources :project_dashboards, only: [:index, :show, :create, :destroy] do
      collection {post :import}
  end

  resources :lead_reports, only: [:index]
  resources :project_visuals, only: [:index]
  resources :test, only: [:index] 
  resources :data_visuals, only: [:index] 
  resources :export_dashboard, only: [:index] 
  resources :inspections,only: [:index,:show,:edit,:organization]
  
  resources :inspection_reports do
      resources :inspections,only: [:show, :create, :destroy, :edit] 
      resources :notes,only: [:show, :create, :destroy] 
      resources :forces,only: [:show, :create, :destroy] 
      collection {put :approved}

  end

 resources :graph, only: [:index] 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/concrete_summary.rb
require 'csv'

class ConcreteSummary < ActiveRecord::Base
	attr_accessible :date, :baseline_early_ind, :baseline_early_cum, :baseline_late_ind, :baseline_late_cum 


	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			ConcreteSummary.create! row.to_hash
			#binding.pry
		end
	end


	
end

app/models/daily_report.rb
class DailyReport < ActiveRecord::Base
	attr_accessible :narrative, :date
	has_many :inspections
	has_many :narratives
	before_create :ensure_date
	
	def ensure_date
		self.date = Date.today unless self.date
	end 	

	has_attached_file :image, styles: {
	    thumb: '100x100>',
	    original: '250x250>'
	}
	
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.ensure_today
		daily_reports = DailyReport.where(date: Date.today)
    
		# ternary operator
		daily_report = daily_reports.present? ? daily_reports.first : DailyReport.create
		# daily_report = if daily_reports.present? 
		#     daily_reports.first 
		#   else 
		#     DailyReport.create
		# end

		daily_report
	end
	
	def self.to_csv
		CSV.generate do |csv|
		csv << column_names
			all.each do |wall|
			csv << wall.attributes.values_at(*column_names)
			end	
		end
	end

end

app/models/force.rb
class Force < ActiveRecord::Base
	attr_accessible :heading, :union147, :union15, :union14, :union731, :union3
	belongs_to :inspection_report
end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
	attr_accessible :heading, :element, :start, :finish, :operation, :scope, :note, :inspector
	 belongs_to :inspection_report
   belongs_to :daily_report
   before_save :ensure_daily_report
	 has_attached_file :image, 
   :styles => { :original => ['250x250>'],:thumb =>['100x100>'] },
   :default_url => "missing.png"

  def ensure_daily_report
    self.daily_report = DailyReport.ensure_today unless self.daily_report
  end

	 validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.search_for(query)
    where('heading LIKE :query OR element LIKE :query OR operation LIKE :query OR inspector LIKE :query ', query: "%#{query}%")
  end
end 

app/models/inspection_report.rb
class InspectionReport < ActiveRecord::Base
attr_accessible :inspector, :date, :contract, :contractor, :shift, :status

	has_many :inspections
	has_many :notes
	has_many :forces

	belongs_to :user

end

app/models/labor.rb
class Labor < ActiveRecord::Base
end

app/models/manhour.rb
class Manhour < ActiveRecord::Base
	attr_accessible :heading
	belongs_to :inspection_report

end

app/models/narrative.rb
class Narrative < ActiveRecord::Base
	attr_accessible :narrative
	belongs_to :daily_report

end

app/models/note.rb
class Note < ActiveRecord::Base
	attr_accessible :observation
	belongs_to :inspection_report
end

app/models/project_dashboard.rb
class ProjectDashboard < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :username, :email, :password, :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 	has_many :inspection_reports


  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "user_prrofile_1.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/manhours_controller.rb
class ManhoursController < ApplicationController
  before_action :set_manhour, only: [:show, :edit, :update, :destroy]

  # GET /manhours
  # GET /manhours.json
  def index
    @manhours = Manhour.all
  end

  # GET /manhours/1
  # GET /manhours/1.json
  def show
  end

  # GET /manhours/new
  def new
    @manhour = Manhour.new
  end

  # GET /manhours/1/edit
  def edit
  end

  # POST /manhours
  # POST /manhours.json
  def create
    @manhour = Manhour.new(manhour_params)

    respond_to do |format|
      if @manhour.save
        format.html { redirect_to @manhour, notice: 'Manhour was successfully created.' }
        format.json { render action: 'show', status: :created, location: @manhour }
      else
        format.html { render action: 'new' }
        format.json { render json: @manhour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manhours/1
  # PATCH/PUT /manhours/1.json
  def update
    respond_to do |format|
      if @manhour.update(manhour_params)
        format.html { redirect_to @manhour, notice: 'Manhour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @manhour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manhours/1
  # DELETE /manhours/1.json
  def destroy
    @manhour.destroy
    respond_to do |format|
      format.html { redirect_to manhours_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manhour
      @manhour = Manhour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manhour_params
      params.require(:manhour).permit(:heading, :union147, :union15,:union14,:union731,:union3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/forces_helper.rb
module ForcesHelper
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/helpers/manhours_helper.rb
module ManhoursHelper
end

app/helpers/narratives_helper.rb
module NarrativesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/manhours/_form.html.erb
<%= form_for(@manhour) do |f| %>
  <% if @manhour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manhour.errors.count, "error") %> prohibited this manhour from being saved:</h2>

      <ul>
      <% @manhour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :heading %><br>
    <%= f.text_field :heading %>
  </div>
  <div class="field">
    <%= f.label :union147 %><br>
    <%= f.text_field :union147 %>
  </div>
  <div class="field">
    <%= f.label :union15 %><br>
    <%= f.text_field :union15 %>
  </div>


<div class="field">
    <%= f.label :union14 %><br>
    <%= f.text_field :union14 %>
  </div>

<div class="field">
    <%= f.label :union731 %><br>
    <%= f.text_field :union731 %>
  </div>

  <div class="field">
    <%= f.label :union3 %><br>
    <%= f.text_field :union3 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manhours/edit.html.erb
<h1>Editing manhour</h1>

<%= render 'form' %>

<%= link_to 'Show', @manhour %> |
<%= link_to 'Back', manhours_path %>

app/views/manhours/index.html.erb
<h1>Listing manhours</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Heading</th>
      <th>Union147</th>
      <th>Union15</th>
      <th>Union14</th>
      <th>Union731</th>
      <th>Union3</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @manhours.each do |manhour| %>
      <tr>
        <td><%= manhour.heading %></td>
        <td><%= manhour.union147 %></td>
        <td><%= manhour.union15 %></td>
        <td><%= manhour.union14 %></td>
        <td><%= manhour.union731 %></td>
        <td><%= manhour.union3 %></td>
        <td><%= link_to 'Show', manhour %></td>
        <td><%= link_to 'Edit', edit_manhour_path(manhour) %></td>
        <td><%= link_to 'Destroy', manhour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manhour', new_manhour_path %>

app/views/manhours/new.html.erb
<h1>New manhour</h1>

<%= render 'form' %>

<%= link_to 'Back', manhours_path %>

app/views/manhours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Heading:</strong>
  <%= @manhour.heading %>
</p>

<p>
  <strong>Union147:</strong>
  <%= @manhour.union147 %>
</p>

<p>
  <strong>Union15:</strong>
  <%= @manhour.union15 %>
</p>

<p>
  <strong>Union14:</strong>
  <%= @manhour.union15 %>
</p>

<p>
  <strong>Union731:</strong>
  <%= @manhour.union15 %>
</p>

<p>
  <strong>Union3:</strong>
  <%= @manhour.union15 %>
</p>

<%= link_to 'Edit', edit_manhour_path(@manhour) %> |
<%= link_to 'Back', manhours_path %>