config/routes.rb
DailyTrack::Application.routes.draw do

  resources :manhours
   resources :inspections

  devise_for :admins
  devise_for :users 

 resources :users

  root 'welcome#home'

  resources :daily_reports do
      resources :daily_reports, only: [:new, :index, :show, :create,]
      resources :narratives,only: [:show, :create, :destroy,]
  end 

  resources :project_dashboards, only: [:index, :show, :create, :destroy] do
      collection {post :import}
  end

  resources :lead_reports, only: [:index]
  resources :project_visuals, only: [:index]
  resources :test, only: [:index] 
  resources :data_visuals, only: [:index] 
  resources :export_dashboard, only: [:index] 
  resources :inspections,only: [:index,:show,:edit,:organization]
  
  resources :inspection_reports do
      resources :inspections,only: [:show, :create, :destroy, :edit] 
      resources :notes,only: [:show, :create, :destroy] 
      resources :forces,only: [:show, :create, :destroy] 
      collection {put :approved}

  end

 resources :graph, only: [:index] 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/concrete_summary.rb
require 'csv'

class ConcreteSummary < ActiveRecord::Base
	attr_accessible :date, :baseline_early_ind, :baseline_early_cum, :baseline_late_ind, :baseline_late_cum 


	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			ConcreteSummary.create! row.to_hash
			#binding.pry
		end
	end


	
end

app/models/daily_report.rb
class DailyReport < ActiveRecord::Base
	attr_accessible :narrative, :date
	has_many :inspections
	has_many :narratives
	before_create :ensure_date
	
	def ensure_date
		self.date = Date.today unless self.date
	end 	

	has_attached_file :image, styles: {
	    thumb: '100x100>',
	    original: '250x250>'
	}
	
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.ensure_today
		daily_reports = DailyReport.where(date: Date.today)
    
		# ternary operator
		daily_report = daily_reports.present? ? daily_reports.first : DailyReport.create
		# daily_report = if daily_reports.present? 
		#     daily_reports.first 
		#   else 
		#     DailyReport.create
		# end

		daily_report
	end
	
	def self.to_csv
		CSV.generate do |csv|
		csv << column_names
			all.each do |wall|
			csv << wall.attributes.values_at(*column_names)
			end	
		end
	end

end

app/models/force.rb
class Force < ActiveRecord::Base
	attr_accessible :heading, :union147, :union15, :union14, :union731, :union3
	belongs_to :inspection_report
end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
	attr_accessible :heading, :element, :start, :finish, :operation, :scope, :note, :inspector
	 belongs_to :inspection_report
   belongs_to :daily_report
   before_save :ensure_daily_report
	 has_attached_file :image, 
   :styles => { :original => ['250x250>'],:thumb =>['100x100>'] },
   :default_url => "missing.png"

  def ensure_daily_report
    self.daily_report = DailyReport.ensure_today unless self.daily_report
  end

	 validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.search_for(query)
    where('heading LIKE :query OR element LIKE :query OR operation LIKE :query OR inspector LIKE :query ', query: "%#{query}%")
  end
end 

app/models/inspection_report.rb
class InspectionReport < ActiveRecord::Base
attr_accessible :inspector, :date, :contract, :contractor, :shift, :status

	has_many :inspections
	has_many :notes
	has_many :forces

	belongs_to :user

end

app/models/labor.rb
class Labor < ActiveRecord::Base
end

app/models/manhour.rb
class Manhour < ActiveRecord::Base
	attr_accessible :heading
	belongs_to :inspection_report

end

app/models/narrative.rb
class Narrative < ActiveRecord::Base
	attr_accessible :narrative
	belongs_to :daily_report

end

app/models/note.rb
class Note < ActiveRecord::Base
	attr_accessible :observation
	belongs_to :inspection_report
end

app/models/project_dashboard.rb
class ProjectDashboard < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :username, :email, :password, :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 	has_many :inspection_reports


  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "user_prrofile_1.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  before_action :authenticate_user!

    def index  
      @inspections = Inspection.search_for(params[:q])
      @walls = Inspection.where(created_at: (Time.now.midnight)..Time.now).order(created_at: :asc)
    end

    def create
      @inspection_report = InspectionReport.find(params[:inspection_report_id])
    	@inspection = @inspection_report.inspections.new(inspection_params)#automatically associates the inspeciton to the report
      @inspection.image = params["inspection"]["image"]
      @inspection.inspector = current_user.username
      @inspection.save
      redirect_to inspection_report_path(@inspection_report)
  	end

  	def show
      @inspections = Inspection.all	  
    	@inspection = @inspections.find(params[:id])
      @inspection_report_current =InspectionReport.where(:inspector => current_user.username).last
    end

  	def destroy
    	@inspection_report = InspectionReport.find(params[:inspection_report_id])
    	@inspection = @inspection_report.inspections.find(params[:id])
    	@inspection.destroy
    	redirect_to inspection_report_path(@inspection_report)
  	end
 
 	  def edit
      @inspection_report_current =InspectionReport.where(:inspector => current_user.username).last
      @inspections = Inspection.all 
    	@inspection = @inspections.find(params[:id])
  	end

      def update
        @inspection = Inspection.find params[:id]
        respond_to do |format|
      if @inspection.update(inspection_params)
        format.html { redirect_to @inspection, notice: 'Inspection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inspeciton.errors, status: :unprocessable_entity }
      end
    end
  end

  def organization
    @walls = Inspection.where(created_at: (Time.now.midnight)..Time.now).order(created_at: :asc)
  end


private
    def inspection_report_params
      params.require(:inspection_report).permit( :date)
    end
    def inspection_params
      params.require(:inspection).permit(:heading, :element, :start, :finish, :operation, :scope, :note, :image )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/forces_helper.rb
module ForcesHelper
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/helpers/manhours_helper.rb
module ManhoursHelper
end

app/helpers/narratives_helper.rb
module NarrativesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inspections/_form.html.erb
<%= form_for([@inspection, @inspection_report.inspections.build]) do |f| %>
  <p>
    <%= f.label :heading %><br>
    <%= f.text_field :heading %>
  </p>
  <p>
    <%= f.label :element %><br>
    <%= f.text_field :element %>
  </p>
  <p>
    <%= f.label :start %><br>
    <%= f.text_field :start %>
  </p>
  <p>
    <%= f.label :end %><br>
    <%= f.text_field :end %>
  </p>
  <p>
    <%= f.label :operation %><br>
    <%= f.text_field :operation %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/inspections/index.html.erb
      <!-- Navigation -->
      <div class="container"> 
        <div class="header">
            <ul class="nav nav-pills pull-right">
                <!-- <li><%= link_to 'Concept', project_visuals_path  %></li> -->
                <li><%= link_to 'Inspection Report', inspection_reports_path  if current_user  %></li>  
                <li><%= link_to 'Daily Report', daily_reports_path  if current_user && current_user.admin? %></li>
                <li><%= link_to 'Lead Report', lead_reports_path  if current_user && current_user.admin? %></li>
                <li><%= link_to 'Search', inspections_path  if current_user && current_user.admin? %></li>
                <li><%= link_to 'Profile', users_path  if current_user  %></li>
                <li><%= link_to 'Enter', users_path  if !current_user  %></li>
                <li> <%= button_to "Sign out", destroy_user_session_path , :class => "btn btn-link" , method: :delete  if current_user%></li>
            </ul>
          <h2 ><%= link_to 'Daily Track', root_path%><h2>
        </div>
      </div> 



<div class ='text-center'>
  <h1 class="text-center">Search Results</h1>
      <%= form_tag "/inspections", method: "GET" do %>
      <%= text_field_tag :q, params[:q] %>
  <p 'text-center'><%= submit_tag "Search",  :class => "btn btn-primary " %></p>
<% end %>

<table class ='table'>
  <tr>
<th>INSPECTOR</th>
<th>TIME</th>
    <th>HEADING</th>
    <th>ELEMENT</th>
    <th>START</th>
    <th>FINISH</th>
    <th>OPERATION</th>
    <th helvetica="3"></th>
  </tr>

<% @inspections.reverse_each do |inspection| %>
  <tr>
    <td><%= inspection.inspector %></td>
     <td><%= inspection.created_at.to_formatted_s(:short) %></td>

    <td><%= inspection.heading %></td>
    <td><%= inspection.element %></td>
    <td><%= inspection.start %></td>
    <td><%= inspection.finish %></td>
    <td><%= inspection.operation %></td>
    <td><%= image_tag inspection.image.url(:thumb) %></td>
  </tr>
<% end -%>

</table>

</div>
<!-- </div> -->

app/views/inspections/organization.html.erb
<p>hello</p>

app/views/inspections/show.html.erb
<table class = "table">
            <h3><tr>

              <th>Heading</th>
              <th>Element</th>
              <th>Start</th>
              <th>Finish</th>
              <th >Scope</th>
              <th>Operation</th>
              <th>Notes</th>


        
              
            </tr></h3>
    
              <h3><tr>
                <td><%= @inspection.heading %></td>
                <td><%= @inspection.element %></td>
                <td><%= @inspection.start %></td>
                <td><%= @inspection.finish %></td>
                <td><%= @inspection.scope %></td>
                <td><%= @inspection.operation %></td>
                <td><%= @inspection.note %></td>
                
              </tr></h3>
      

          </table>


<div class = "text-center" >
  <h3><u><td> <%= link_to 'Edit Inspection', edit_inspection_path(@inspection) %></td></h3></u>
  <h1><u><%= link_to 'Back to the Report', inspection_report_path(@inspection_report_current) %> </h1></u>
</div>