config/routes.rb
DailyTrack::Application.routes.draw do

  resources :manhours
   resources :inspections

  devise_for :admins
  devise_for :users 

 resources :users

  root 'welcome#home'

  resources :daily_reports do
      resources :daily_reports, only: [:new, :index, :show, :create,]
      resources :narratives,only: [:show, :create, :destroy,]
  end 

  resources :project_dashboards, only: [:index, :show, :create, :destroy] do
      collection {post :import}
  end

  resources :lead_reports, only: [:index]
  resources :project_visuals, only: [:index]
  resources :test, only: [:index] 
  resources :data_visuals, only: [:index] 
  resources :export_dashboard, only: [:index] 
  resources :inspections,only: [:index,:show,:edit,:organization]
  
  resources :inspection_reports do
      resources :inspections,only: [:show, :create, :destroy, :edit] 
      resources :notes,only: [:show, :create, :destroy] 
      resources :forces,only: [:show, :create, :destroy] 
      collection {put :approved}

  end

 resources :graph, only: [:index] 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/concrete_summary.rb
require 'csv'

class ConcreteSummary < ActiveRecord::Base
	attr_accessible :date, :baseline_early_ind, :baseline_early_cum, :baseline_late_ind, :baseline_late_cum 


	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			ConcreteSummary.create! row.to_hash
			#binding.pry
		end
	end


	
end

app/models/daily_report.rb
class DailyReport < ActiveRecord::Base
	attr_accessible :narrative, :date
	has_many :inspections
	has_many :narratives
	before_create :ensure_date
	
	def ensure_date
		self.date = Date.today unless self.date
	end 	

	has_attached_file :image, styles: {
	    thumb: '100x100>',
	    original: '250x250>'
	}
	
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.ensure_today
		daily_reports = DailyReport.where(date: Date.today)
    
		# ternary operator
		daily_report = daily_reports.present? ? daily_reports.first : DailyReport.create
		# daily_report = if daily_reports.present? 
		#     daily_reports.first 
		#   else 
		#     DailyReport.create
		# end

		daily_report
	end
	
	def self.to_csv
		CSV.generate do |csv|
		csv << column_names
			all.each do |wall|
			csv << wall.attributes.values_at(*column_names)
			end	
		end
	end

end

app/models/force.rb
class Force < ActiveRecord::Base
	attr_accessible :heading, :union147, :union15, :union14, :union731, :union3
	belongs_to :inspection_report
end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
	attr_accessible :heading, :element, :start, :finish, :operation, :scope, :note, :inspector
	 belongs_to :inspection_report
   belongs_to :daily_report
   before_save :ensure_daily_report
	 has_attached_file :image, 
   :styles => { :original => ['250x250>'],:thumb =>['100x100>'] },
   :default_url => "missing.png"

  def ensure_daily_report
    self.daily_report = DailyReport.ensure_today unless self.daily_report
  end

	 validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.search_for(query)
    where('heading LIKE :query OR element LIKE :query OR operation LIKE :query OR inspector LIKE :query ', query: "%#{query}%")
  end
end 

app/models/inspection_report.rb
class InspectionReport < ActiveRecord::Base
attr_accessible :inspector, :date, :contract, :contractor, :shift, :status

	has_many :inspections
	has_many :notes
	has_many :forces

	belongs_to :user

end

app/models/labor.rb
class Labor < ActiveRecord::Base
end

app/models/manhour.rb
class Manhour < ActiveRecord::Base
	attr_accessible :heading
	belongs_to :inspection_report

end

app/models/narrative.rb
class Narrative < ActiveRecord::Base
	attr_accessible :narrative
	belongs_to :daily_report

end

app/models/note.rb
class Note < ActiveRecord::Base
	attr_accessible :observation
	belongs_to :inspection_report
end

app/models/project_dashboard.rb
class ProjectDashboard < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :username, :email, :password, :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 	has_many :inspection_reports


  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "user_prrofile_1.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
  before_action :authenticate_user!
	
	def index
    @daily_report= DailyReport.ensure_today  
    @inspections = @daily_report.inspections.order(created_at: :asc)  
    @walls = @daily_report.inspections.where("element = ?", "WALL").order(created_at: :asc) 
    @slabs = @daily_report.inspections.where("element = ?", "SLAB").order(created_at: :asc) 
    @arches = @daily_report.inspections.where("element = ?", "ARCH").order(created_at: :asc)  
    @user = current_user
  end  

	def new
		@daily_report = DailyReport.ensure_today
	end
	
	def create
      date_params = params['/daily_reports']
      #year = date_params["date(1i)"]
      #month = date_params["date(2i)"]
      #day = date_params["date(3i)"]
      #@date = Date.new(year.to_i, month.to_i, day.to_i)
      @daily_report = DailyReport.find_or_initialize_by_date(date_params)
      if @daily_report.save
  			redirect_to @daily_report 
  		else
  			render 'new'
  		end
  	end

  def show
    	@daily_report = DailyReport.find(params[:id])
      @inspections = @daily_report.inspections.order(created_at: :asc)  
      @walls = @daily_report.inspections.where("element = ?", "WALL").order(created_at: :asc) 
      @slabs = @daily_report.inspections.where("element = ?", "SLAB").order(created_at: :asc) 
      @arches = @daily_report.inspections.where("element = ?", "ARCH").order(created_at: :asc)
      @user = current_user
      
      respond_to do |format|
        format.html
        format.csv{send_data text: @walls.to_csv }
        format.xls
      end  	
    end

  def destroy
      @observation = @daily_report.observations.find(params[:id])
      @observation.destroy
      redirect_to daily_reports_path 
  end
	
	private
  	def daily_reports_params
    	params.require(:daily_report).permit(:narrative, :date)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/helpers/forces_helper.rb
module ForcesHelper
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/helpers/manhours_helper.rb
module ManhoursHelper
end

app/helpers/narratives_helper.rb
module NarrativesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/daily_reports/index.html.erb
      <div class="container">
        <div class="header">
            <ul class="nav nav-pills pull-right">
                <!-- <li><%= link_to 'Concept', project_visuals_path  %></li> -->
                <li><%= link_to 'Inspection Report', inspection_reports_path  if current_user  %></li>  
                <li><%= link_to 'Daily Report', daily_reports_path  if current_user && current_user.admin? %></li>
                <li><%= link_to 'Lead Report', lead_reports_path  if current_user && current_user.admin? %></li>
                <!-- <li><%= link_to 'Dashboard', project_dashboards_path  if current_user && current_user.admin? %></li> -->
                <li><%= link_to 'Search', inspections_path  if current_user && current_user.admin? %></li>
                <li><%= link_to 'Profile', users_path  if current_user  %></li>
                <li><%= link_to 'Enter', users_path  if !current_user  %></li>
                <li> <%= button_to "Sign out", destroy_user_session_path , :class => "btn btn-link" , method: :delete  if current_user%></li>
            </ul>
          <h2 ><%= link_to 'Daily Track', root_path%><h2>
        </div>
      </div> 



<div class = "container">
  <h1 class="text-center ">Daily Report</h1>
  <div class="text-center ">  
  <br>     
  <p ><%= image_tag(@user.image.url(:thumb)) %></p>
  <p><%= button_to  "Export Excel",daily_reports_path(format: "xls"), :class => "btn ", :method => :get %></p>
</div>

<div class='row'>
  <div class ='span8'>
    <h3>Summary</h3>
     <table class="table" >
              <tr>
                <th>Heading</th>
                <th>Element</th>
                <th>Start</th>
                <th>Finish</th>
                <th>Operation</th>

                <th>Images</th>

              </tr>


            <% @inspections.each do |inspection| %>
              <tr>
                <td><%= inspection.heading %></td>
                <td><%= inspection.element %></td>
                <td><%= inspection.start %></td>
                <td><%= inspection.finish %></td>
                <td><%= inspection.operation %></td>
                <td><%= image_tag inspection.image.url(:thumb) %></td>
              </tr>
            <% end -%>


            <% @walls.each do |wall| %>
              <tr>
                <td><%= wall.heading %></td>
                <td><%= wall.element %></td>
                <td><%= wall.start %></td>
                <td><%= wall.finish %></td>
                <td><%= wall.operation %></td>
                <td><%= image_tag wall.image.url(:thumb) %></td>
              </tr>
            <% end -%>


             <% @slabs.each do |slab| %>
                <tr>
                  <td><%= slab.heading %></td>
                  <td><%= slab.element %></td>
                  <td><%= slab.start %></td>
                  <td><%= slab.finish %></td>
                  <td><%= slab.operation %></td>
                  <td><%= image_tag slab.image.url(:thumb) %></td>
                </tr>
            <% end -%>


             <% @arches.each do |arch| %>
              <tr>
                <td><%= arch.heading %></td>
                <td><%= arch.element %></td>
                <td><%= arch.start %></td>
                <td><%= arch.finish %></td>
                <td><%= arch.operation %></td>
                <td><%= image_tag arch.image.url(:thumb) %></td>
              </tr>
              <% end -%>      
          </table>
  <!-- 
          <h3>Notes:</h3>
          <table>
              <% @daily_report.narratives.each do |narrative| %>
                <p><%= narrative.narrative %>
                <%= link_to '+', [narrative.daily_report, narrative],
                         method: :delete,
                         data: { confirm: 'Are you sure?' } %>
                  <% end %>
                </p>
          </table>

          <h3>Create Note:</h3>
              <%= form_for([@daily_report, @daily_report.narratives.build]) do |f| %>
                <table>
                  <tr>
                    <%= f.text_area :narrative %></th> 
                  </tr>
                </table>  
                    <p><%= f.submit class: 'btn btn-primary' , value: 'Create Note '%></p>
          <% end %> -->

        </div>

      <div class ='span1'>
      </div>
      
      <div class ='span3'>
          <h3>Search</h3>
            <%= form_for daily_reports_path do |f| %>
              <h2><%= f.date_field :date %></h2>
            <%= f.submit 'Submit', class: 'btn btn-primary', value: 'Find' %>
          <% end %> 
          
      </div>

</div>

<div>
    <% @inspections.each do |inspection| %>
      <tr>
    <td><%= image_tag inspection.image.url(:original) %></td>
  </tr>
<% end -%>


    <% @walls.each do |wall| %>
      <tr>
    <td><%= image_tag wall.image.url(:original) %></td>
  </tr>
<% end -%>

<% @slabs.each do |slab| %>
  <tr>
    <td><%= image_tag slab.image.url(:original) %></td>
  </tr>
<% end -%>

<% @arches.each do |arch| %>
  <tr>
    <td><%= image_tag arch.image.url(:original) %></td>
  </tr>
<% end -%>
</div>

app/views/daily_reports/index.xls.erb
<h3>SUMMARY</h3>
<table>
  <tr>
    <th>HEADING</th>
    <th>ELEMENT</th>
    <th>START</th>
    <th>FINISH</th>
    <th>OPERATION</th>
    <th helvetica="3"></th>
  </tr>

            <% @inspections.each do |inspection| %>
            <tr>
              <td><%= inspection.heading %></td>
              <td><%= inspection.element %></td>
              <td><%= inspection.start %></td>
              <td><%= inspection.finish %></td>
              <td><%= inspection.operation %></td>
              <td><%= image_tag inspection.image.url(:thumb) %></td>
            </tr>
          <% end -%>


<% @walls.each do |wall| %>
  <tr>
    <td><%= wall.heading %></td>
    <td><%= wall.element %></td>
    <td><%= wall.start %></td>
    <td><%= wall.finish %></td>
    <td><%= wall.operation %></td>
  </tr>
   <% end -%>
  
   <% @slabs.each do |slab| %>
  <tr>
    <td><%= slab.heading %></td>
    <td><%= slab.element %></td>
    <td><%= slab.start %></td>
    <td><%= slab.finish %></td>
    <td><%= slab.operation %></td>
  </tr>
  <% end -%>

   <% @arches.each do |slab| %>
  <tr>
    <td><%= arch.heading %></td>
    <td><%= arch.element %></td>
    <td><%= arch.start %></td>
    <td><%= arch.finish %></td>
    <td><%= arch.operation %></td>
  </tr>
  <% end -%>
  
  </table>

app/views/daily_reports/new.html.erb
<h2>New daily Report</h2>
<%= form_for @daily_report do |f| %>
  <p>
    <%= f.label :NARRATIVE  %><br>
    <%= f.text_area :narrative %>
  </p>
  
  <p>
    <%= f.submit 'New Report', class: 'button' %> 
    <!-- Where do I control the submit button is rendered? -->
  </p>
<% end %>

app/views/daily_reports/show.html.erb
<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>

<p class = "text-center"><u><strong><%= link_to 'Today',daily_reports_path, :class => "btn  "%><strong></u></p>
<h1 class="text-center ">Daily Report</h1>

  <div class="text-center" >       
        <!-- <p>    
            <%= @user.username%>
        </p> -->
<br>
    <!--     <p>           
            <%= link_to 'VDC Coordinator', users_path  if current_user.admin? %>        
        </p> -->
        <p ><%= image_tag(@user.image.url(:thumb)) %></p>
  </div>

<div class="text-center" > 
<%= button_to  "Export Excel", daily_report_path(format: "xls"), :class => "btn btn-primary ", :method => :get %>
</div>


    <div class="text-center">
   
  
        <br>
        <table class="table" >
          <tr>
            <th>Heading</th>
            <th>Element</th>
            <th>Start</th>
            <th>Finish</th>
            <th>Operation</th>
            <th>Images</th>
          </tr>


          <% @inspections.each do |inspection| %>
            <tr>
              <td><%= inspection.heading %></td>
              <td><%= inspection.element %></td>
              <td><%= inspection.start %></td>
              <td><%= inspection.finish %></td>
              <td><%= inspection.operation %></td>
              <td><%= image_tag inspection.image.url(:thumb) %></td>
            </tr>
          <% end -%>
          
          <% @walls.each do |wall| %>
            <tr>
              <td><%= wall.heading %></td>
              <td><%= wall.element %></td>
              <td><%= wall.start %></td>
              <td><%= wall.finish %></td>
              <td><%= wall.operation %></td>
              <td><%= image_tag wall.image.url(:thumb) %></td>
            </tr>
          <% end -%>
           <% @slabs.each do |slab| %>
              <tr>
                <td><%= slab.heading %></td>
                <td><%= slab.element %></td>
                <td><%= slab.start %></td>
                <td><%= slab.finish %></td>
                <td><%= slab.operation %></td>
                <td><%= image_tag slab.image.url(:thumb) %></td>
              </tr>
          <% end -%>
           <% @arches.each do |arch| %>
            <tr>
              <td><%= arch.heading %></td>
              <td><%= arch.element %></td>
              <td><%= arch.start %></td>
              <td><%= arch.finish %></td>
              <td><%= arch.operation %></td>
              <td><%= image_tag arch.image.url(:thumb) %></td>
            </tr>
            <% end -%>      
        </table>
    
    </div>  


<h3 class="text-center ">Images</h3>
    <% @inspections.each do |inspection| %>
      <tr>
    <td><%= image_tag inspection.image.url(:original) %></td>
  </tr>
<% end -%>


<% @walls.each do |wall| %>
  <tr>
    <td><%= image_tag wall.image.url(:original) %></td>
  </tr>
   <% end -%>

   <% @slabs.each do |slab| %>
  <tr>
    <td><%= image_tag slab.image.url(:original) %></td>
  </tr>
   <% end -%>

app/views/daily_reports/show.xls.erb
<h3>SUMMARY</h3>
<table>
  <tr>
    <th>HEADING</th>
    <th>ELEMENT</th>
    <th>START</th>
    <th>FINISH</th>
    <th>OPERATION</th>
    <th helvetica="3"></th>
  </tr>

            <% @inspections.each do |inspection| %>
            <tr>
              <td><%= inspection.heading %></td>
              <td><%= inspection.element %></td>
              <td><%= inspection.start %></td>
              <td><%= inspection.finish %></td>
              <td><%= inspection.operation %></td>
              <td><%= image_tag inspection.image.url(:thumb) %></td>
            </tr>
          <% end -%>

<% @walls.each do |wall| %>
  <tr>
    <td><%= wall.heading %></td>
    <td><%= wall.element %></td>
    <td><%= wall.start %></td>
    <td><%= wall.finish %></td>
    <td><%= wall.operation %></td>
  </tr>
   <% end -%>
   <% @slabs.each do |slab| %>
  <tr>
    <td><%= slab.heading %></td>
    <td><%= slab.element %></td>
    <td><%= slab.start %></td>
    <td><%= slab.finish %></td>
    <td><%= slab.operation %></td>
  </tr>
  <% end -%>
  </table>